# Generated by Django 5.0.6 on 2024-05-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
