# Generated by Django 5.0.6 on 2024-05-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
