version: '3.8'

services:
  db:
    image: postgres:13
    container_name: TaskManager-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.dev
    environment:
      - POSTGRES_DB=$(POSTGRES_DB)
      - POSTGRES_USER=$(POSTGRES_USER)
      - POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)
    networks:
      - app_network

  web:
    container_name: TaskManager-web
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: /app_entrypoint.sh
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - env/.env.dev
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
