version: '3.8'

services:
  db:
    image: postgres:13
    container_name: DjanTask-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.dev
    networks:
      - app_network

  web:
    container_name: DjanTask-web
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/src
    ports:
      - "8001:8000"
    env_file:
      - env/.env.dev
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
