version: '3.8'

services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: DjanTask-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.dev
    networks:
      - app_network

  web:
    container_name: DjanTask-web
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: /home/app/app_entrypoint.sh
    env_file:
      - env/.env.dev
    volumes:
      - .:/home/app/
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  celery-beat:
    container_name: DjanTask-celery-beat
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A djantasks beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - env/.env.dev
    volumes:
      - .:/home/app/
    depends_on:
      - db
      - redis
    networks:
      - app_network

  celery-worker:
    container_name: DjanTask-celery-worker
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A djantasks worker -l INFO --autoscale=4,1
    env_file:
      - env/.env.dev
    volumes:
      - .:/home/app/
    depends_on:
      - db
      - redis
    networks:
      - app_network

  redis:
    image: redis:7.0.12-alpine3.18
    container_name: DjanTask-redis
    networks:
      - app_network


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
