# Generated by Django 5.0.6 on 2024-06-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='status',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
