# Generated by Django 5.0.6 on 2024-06-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('IN', 'In Progress'), ('CL', 'Closed'), ('EX', 'Expired')], default='OP', max_length=20),
        ),
    ]
