# Generated by Django 5.0.6 on 2024-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_alter_workspace_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='status',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
