# Generated by Django 5.0.6 on 2024-05-23 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_alter_workspace_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='shared_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
