# Generated by Django 5.0.6 on 2024-05-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0010_alter_workspace_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
