version: '3.9'

services:
  db:
    container_name: djan_db
    image: postgres:16.3-alpine3.20
    volumes:
      - postgers_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app_network

  redis:
    container_name: djan_redis
    image: redis:7.2.5-alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  web:
    container_name: DjanTask
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # command: ./docker/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgers_data:
